import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Poppins } from "next/font/google";
import MyState from "@/context/MyState";
import { Metadata } from "next";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";

const poppins = Poppins({ subsets: ["latin"], weight: ["500"] });

export const metadata: Metadata = {
  title: {
    default: "social media app",
    template: "social media app - %s",
  },
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <body className={poppins.className} suppressHydrationWarning>
      <NextTopLoader color="#22c55e" height={3} showSpinner={false} />
      <MyState>{children}</MyState>
      <ToastContainer position="top-center" autoClose={1500} />
    </body>
  </html>
);

export default RootLayout;
